# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:12
from __future__ import unicode_literals

from django.db import migrations

def create_my_user(apps, schema_editor):
    from django.contrib.auth.models import User
    User.objects.create_superuser('test', 'test@gmail.com', 'test')

class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_profile'),
    ]

    operations = [
        migrations.RunPython(create_my_user),
        ]
