# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:31
from __future__ import unicode_literals

from django.db import migrations

def create_default_tags(apps, schema_editor):
    from ..models import Tag
    tag = Tag(name='SuperMarket', color='blue')
    tag.save()
    tag = Tag(name='Drugstore', color='green')
    tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20170625_2212'),
    ]

    operations = [
        migrations.RunPython(create_default_tags),
        ]
