# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "ubuntu/trusty64"
	config.vm.network "private_network", ip: "192.168.8.115"

	if File.directory?(File.expand_path("../../super_market_list"))
    	config.vm.synced_folder "../../super_market_list", "/home/vagrant/super_market_list"
  	end
end
