# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "ubuntu/trusty64"
	config.vm.network :private_network, ip: "192.168.68.8"

	config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = "dev_env"
    end

	config.vm.provision "shell", path: "prov.sh"

	if File.directory?(File.expand_path("../../super_market_list"))
    	config.vm.synced_folder "../../super_market_list/awesomemarketlist", "/home/vagrant/awesomemarketlist"
  	end
end
